- name: be sure MacVim is installed
  homebrew: name=macvim state=present options=with-lua,override-system-vim

- name: be sure exuberant-ctags is installed
  homebrew: name=ctags state=present

- name: be sure vim configurations are updated
  git: repo=git@github.com:renanivo/dotvim.git dest=~/.vim
  notify:
    - make dotVIM
    - install instant-markdown-d node package
    - install redcarpet gem
    - install pygments.rb gem

- name: be sure .vimrc is updated
  get_url: url=https://gist.githubusercontent.com/renanivo/415001/raw/f50451264245c9a33968690d548de490ef236fc9/.vimrc
           dest=~/.vimrc
