- name: be sure pyenv is installed and updated
  homebrew: name=pyenv state=latest

- name: install python compiling dependencies
  homebrew: name={{item}} state=latest
  with_items:
    - readline
    - xz

- name: install pythons with pyenv
  shell: 'pyenv install {{ item }}'
  with_items: '{{ python_versions }}'

- name: set global version of python
  shell: 'pyenv global {{ global_python_version }}'

- name: install user pip packages
  pip: name={{ user_pip_packages }} state=latest executable='pip3' extra_args='--user'
