- name: be sure python2 is installed
  homebrew: name=python state=latest

- name: be sure python3 is installed
  homebrew: name=python3 state=latest

- name: install cryptography package globally
  pip: name=cryptography extra_args="--user" state=latest
  environment:
    LDFLAGS: "-L/usr/local/opt/openssl/lib"
    CFLAGS: "-I/usr/local/opt/openssl/include"

- name: be sure global pip packages are installed
  pip: name={{ item }} extra_args="--user" state=latest
  with_items: global_pip_packages
