- name: be sure fish shell is installed
  homebrew: name=fish state=latest

- name: be sure fish configuration directory exists
  file: path=~/.config/fish state=directory

- name: be sure fish configuration is updated
  copy: src=config.fish dest=~/.config/fish/config.fish

- name: be sure virtualfish is installed
  pip: name=virtualfish extra_args="--user" state=latest

- name: be sure virtualfish folder exists
  file: path=/Users/{{ ansible_user_id }}/.virtualenvs state=directory

- name: retrieve current shells
  command: cat /etc/shells
  register: shells
  changed_when: false

- name: be sure fish is in /etc/shells
  shell: echo "/usr/local/bin/fish" >> /etc/shells
  become: yes
  when: "'fish' not in shells.stdout"

- name: be sure fish is the default shell
  shell: chsh -s /usr/local/bin/fish {{ ansible_user_id }}
  become: yes
  register: output
  changed_when: "'no changes made' not in output.stderr"
