os:
    - osx

branches:
    only:
        - master

language: python

python:
    - "2.7"

install:
    - pip install ansible

before_script:
    - rm -rf ~/.vim
    - cp group_vars/workstation.example group_vars/workstation

script: ansible-playbook workstation.yml -vv
