os:
    - osx

branches:
    only:
        - master

script: ansible-playbook workstation.yml -vv

before_script:
    - sudo pip install ansible
    - rm -rf ~/.vim
    - cp group_vars/workstation.example group_vars/workstation
