- name: be sure there's a bin folder into the home folder
  command: mkdir ~/bin creates=~/bin

- name: be sure delete-merged script is updated
  get_url: url=https://gist.github.com/renanivo/4990090/raw/7b3d5ab9e396a0ab7b23f288da79eb41798c67ef/delete-merged.sh
           dest=~/bin/delete-merged

- name: be sure delete-merged script is executable
  file: path=~/bin/delete-merged mode=0540

- name: be sure homebrew packages of tools are installed
  homebrew: name={{ item }} state=latest
  with_items: brew_packages

- name: be sure pip packages of tools are installed
  pip: name={{ item }} extra_args="--user" state=latest
  with_items: pip_packages

- name: install tools using ruby gems
  gem: name={{ item }} state=latest
  with_items: gem_packages

- name: be sure homebrew cask packages of all tools are installed
  homebrew_cask: name={{ item }} state=present
  with_items: brew_cask_packages

- name: be sure all browsers are installed
  homebrew_cask: name={{ item }} state=present
  with_items: browsers

- name: be sure "with" tool is installed
  pip: name=with executable=pip3 state=latest
