brew_packages:
    - ack
    - gnu-sed
    - hub
    - nmap
    - tree
    - wget
    - editorconfig

brew_cask_packages:
    - iterm2
    - xquartz

gem_packages:
    - travis

browsers:
    - google-chrome
